parameters:
  dungeon_map:
    -
      #0,0
      - { name: Forge, id: 1 }
      #0,1
      - { name: Summoning Room, id: 2 }
      #0,2
      - { name: Jail, id: 3 }
    -
      #1,0
      - { name: Chapel, id: 4 }
      #1,1
      - { name: Laboratory, id: 5 }
      #1,2
      - { name: Dormitory, id: 6 }
    -
      #2,0
      - { name: Armory, id: 7 }
      #2,1
      - { name: Entrance, id: 8 }
      #2,2
      - { name: Courthall, id: 9 }