parameters:
  dungeon_map:
    -
      #0,0
      - { name: room 5, id: 1 }
      #0,1
      - { name: room 4, id: 2 }
      #0,2
      - { name: room 3, id: 3 }
    -
      #1,0
      - { name: room 2, id: 4 }
      #1,1
      - { name: entrance, id: 5 }
      #1,2
      - { name: room 1, id: 6 }